### ISSUE TITLE
Search functinality

### ISSUE THREAD

**Issue by yeole-rohan** [yeole-rohan/Open-Source-Music-Player#2]
Implement search functionality for platform.

Search by - 
1. Artist
2. Album
3. Song Name

**Comment by Mahboob-A** [comment]
Hi, I have added the search functionality in the project. #7

**Comment by yeole-rohan** [comment]
Thank you so much for working on an Open source project. You can put
https://github.com/yeole-rohan/Open-Source-Music-Player/pull/7 link to your
resume or wherever you wish.

All the best for new work and future projects.

**Comment by yeole-rohan** [comment]
Feel free to share the following link to your friend to showcase your skill.

https://www.youtube.com/post/UgkxWFHV_aGJgvkDzc_oB92afa6WLLbNVHxN
